name: Webpack Build

on:
  push:
    branches:
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
    matrix:
      node-version: [14.x, 12.x, 10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: |
        npm install
    - name: npm build
      run: |
        npm run build
      env:
        CI: true
